### ISSUE TITLE
Lights show as on

### ISSUE THREAD

**Issue by danielclindsay** [wez/govee-lan-hass#11]
My 3 Govee lights show as on in Home Ass. even though they are turned off.

Anyone else experience this? Any help? 

TIA

**Comment by wez** [comment]
If you add this to your `configuration.yaml` and then restart home assistant, you'll get verbose logging that might reveal more about what's happening:

```yaml
logger:
  logs:
    custom_components.govee_lan: debug
    govee_led_wez: debug
```
