### ISSUE TITLE
Transitions not supported?

### ISSUE THREAD

**Issue by Limekiller** [wez/govee-lan-hass#38]
Thanks for the excellent integration. I have it working, but I would like the lights to smoothly interpolate between states. The `transition` value seems to be ignored. Do Govee lights not support this?

Here is an example of an automation step that is working, aside from the transition:
```
service: light.turn_on
data:
  color_temp: 435
  transition: 30
target:
  device_id: 8cfced2707a49b49ee055ce04261bbda
```
