### ISSUE TITLE
Scene restoration not working properly

### ISSUE THREAD

**Issue by BottlecapDave** [wez/govee-lan-hass#44]
Hello. I'm trying to restore the state of my lights which have a scene activated outside of HA via alexa. However it doesn't seem to be working properly.

My automation is as follows

```
- alias: Kitchen - Dishwasher Ready Alert
  id: 28E0F36B-CDF0-4BB5-BF4D-BB16B354E75C
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_occupied
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.is_dishwasher_finished
    state: 'on'
  action:
  - service: scene.create
    data:
      scene_id: kitchen_lights
      snapshot_entities: light.kitchen_bottom_lights
  - delay: 00:00:02
  - service: media_player.play_media
    data:
      media_content_type: custom
      media_content_id: turn on dishwasher alert
    target:
      entity_id: media_player.kitchen_echo
  - delay: 00:00:10
  - service: scene.turn_on
    target:
      entity_id: scene.kitchen_lights
```

If the lights started off, they're not always restoring to their off state. If the lights are on, then they're not always restoring to their original state.
